// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ELZmKdG169-nW27dIZAtZMg3ahBSjOg',
    appId: '1:1056936721175:web:a1710997340e1a2e525552',
    messagingSenderId: '1056936721175',
    projectId: 'edupoint-8e35b',
    authDomain: 'edupoint-8e35b.firebaseapp.com',
    storageBucket: 'edupoint-8e35b.appspot.com',
    measurementId: 'G-4R77S0KQTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj54qtiaBAJqfR1ivFsNFPDWFLXlwI9dg',
    appId: '1:1056936721175:android:5c569c1fa5f20a91525552',
    messagingSenderId: '1056936721175',
    projectId: 'edupoint-8e35b',
    storageBucket: 'edupoint-8e35b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZv-b3WYh7s6D_g-z13HkzWz_KdGcewYY',
    appId: '1:1056936721175:ios:629f93950d87ec63525552',
    messagingSenderId: '1056936721175',
    projectId: 'edupoint-8e35b',
    storageBucket: 'edupoint-8e35b.appspot.com',
    iosClientId: '1056936721175-jc69qlmfvodis090ekh66duva3q8sbjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZv-b3WYh7s6D_g-z13HkzWz_KdGcewYY',
    appId: '1:1056936721175:ios:629f93950d87ec63525552',
    messagingSenderId: '1056936721175',
    projectId: 'edupoint-8e35b',
    storageBucket: 'edupoint-8e35b.appspot.com',
    iosClientId: '1056936721175-jc69qlmfvodis090ekh66duva3q8sbjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduPoint',
  );
}
